stream {
    upstream https://192.168.1.50:443 {
        # Replace with the IP/domain and port of your NGINX Gateway API
        server argosrv.ssbn.se;
    }

    server {
        listen 443;
        # Forwards raw TCP packets directly to the Gateway API
        proxy_pass https://192.168.1.50:443;

        # Optional: Optimizes TCP performance for TLS
	# proxy_buffer_size 16k;
    }
}
