server {
    listen 443 ssl ;
    server_name s3web.ssbn.se ;
    
    ssl_certificate /etc/pki/tls/certs/s3web.crt ;
    ssl_certificate_key /etc/pki/tls/keys/s3web.key ;
        
    location / {
        proxy_pass http://192.168.1.50 ;
        include proxy_params;
    }
}
